# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 10
  
[[main]]
  name = "Skills"
  url = "#skills"
  weight = 20

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 35
  
[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30
  
[[main]]
   name = "Contact me"
   url = "#contact"
   weight = 40
   
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
   name = "Resume"
   url = "files/resume.pdf"
   weight = 50

[[main]]
   name = "Coursework"
   url = "files/coursework.pdf"
   weight = 60
   

