baseurl = "/"
languageCode = "en-us"
title = "Anthony Yoskovich"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About Me (Anthony)"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ayoskovich"
    weight = 2
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/ayoskovich/"
    weight = 3
    
[[menu.main]]
    name = "Resume"
    weight = 4

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
