baseurl: "/"
languageCode: "en-us"
title: "A minimal Hugo website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Blog
      url: ""
      weight: 1
    - name: About Me
      url: "about/"
      weight: 2
    - name: Tags
      url: "tags/"
      weight: 3
    - name: RSS
      url: "index.xml"

params:
  description: "A website built through Hugo and blogdown."
  footer: "Anthony Yoskovich 2019 -- {Year} | _[Github](https://github.com/ayoskovich)_"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
