baseurl = "/"
languageCode = "en-us"
title = "Anthony Yoskovich"
theme = "hugo-xmin"


[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

[params]
    description = "A website built through Hugo and blogdown."
    footer = "Anthony Yoskovich 2020 | [Github](https://github.com/ayoskovich) | [LinkedIn](https://www.linkedin.com/in/ayoskovich/)"
