---
title: How Statistics Has Ruined My Ability To Have Opinions
author: ''
date: '2020-03-26'
slug: how-statistics-has-ruined-my-ability-to-have-opinions
categories: []
tags: []
subtitle: ''
summary: 'A reflection on an unintended consequence of studying statistics.'
authors: []
lastmod: '2020-03-26T13:33:06-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---



&emsp; For the past 4 years I have been studying statistics. Doing lots of practice problems, playing around with data, and reading textbooks. I've become a bit more familiar with the statistical way of thinking, how to analyze problems in terms of distributions rather than single numbers, and how to work with uncertainty. As much as I've loved this, it has had quite the unexpected consequence in my personal life.

### I find it hard to have an opinion about anything.

<br>

&emsp; Thinking about a data generating process as single shot ocurrences isn't a good way to frame problems. A better way would be to ask, "What would happen if we did this thing a bunch of times". When attempting to effectively evaluate hypotheses, thinking about the distribution of events is often more helpful than looking at single occurrences. You don't hear about clinical trials with 1 patient or a brake pad company testing on 1 car. We want the largest sample possible because it gives us the clearest picture of the population and reduces variability.

&emsp; Now back to my life (it is my website after all). Go out to a restaurant and have a bad experience? Well, I've only been there once so maybe it was just an off night. Take a new route home from work? Wow that was quick! But wait, I'm not taking into account the time of day or day of the week. 


&emsp; I can't help but be reminded of these scenes from Silicon Valley (NSFW language).

<iframe width="300" height="300" src="https://www.youtube.com/embed/OaFTpWYCzUk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="300" height="300" src="https://www.youtube.com/embed/VmOd27UwTsg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
